name: Build the dashboards as code
description: Run the `dac build` command of percli to build the dashboards as code
inputs:
  directory:
    description: Path to the directory containing the resources consumed by the command.
    required: false
  file:
    description: Path to the file that contains the resources consumed by the command.
    required: false
runs:
  using: composite
  steps:
    - name: Run the `dac build` command
      run: |
        percli dac build \
          $([[ -n "${{ inputs.directory }}" ]] && echo "-d ${{ inputs.directory }}") \
          $([[ -n "${{ inputs.file }}" ]] && echo "-f ${{ inputs.file }}")
      shell: bash
