name: Build the dashboards as code
description: Run the `lint` command of percli to validate the dashboards
inputs:
  directory:
    description: Path to the directory containing the resources consumed by the command.
    required: false
  file:
    description: Path to the file that contains the resources consumed by the command.
    required: false
  online:
    description: When enabled, it can request the API to make additional validation.
    required: false
runs:
  using: composite
  steps:
    - name: Run the `lint` command
      run: |
        percli lint \
          $([[ -n "${{ inputs.directory }}" ]] && echo "-d ${{ inputs.directory }}") \
          $([[ -n "${{ inputs.file }}" ]] && echo "-f ${{ inputs.file }}") \
          $([[ -n "${{ inputs.online }}" ]] && echo "--online ${{ inputs.online }}")
      shell: bash
