name: "Build the dashboards as code"
description: "Run the `lint` command of percli to validate the dashboards"
inputs:
  directory:
    description: Path to the directory containing the resources consumed by the command.
    required: false
  file:
    description: Path to the file that contains the resources consumed by the command.
    required: false
runs:
  using: composite
  steps:
    - name: Validate inputs
      run: |
        if [[ -z "${{ inputs.directory }}" && -z "${{ inputs.file }}" ]]; then
          echo "Error: Either 'directory' or 'file' must be provided." >&2
          exit 1
        fi
        if [[ -n "${{ inputs.directory }}" && -n "${{ inputs.file }}" ]]; then
          echo "Error: Only one of 'directory' or 'file' can be provided, not both." >&2
          exit 1
        fi
      shell: bash

    - name: Run the `lint` command
      run: |
        if [[ -n "${{ inputs.directory }}" ]]; then
          percli lint -d "${{ inputs.directory }}"
        elif [[ -n "${{ inputs.file }}" ]]; then
          percli lint -f "${{ inputs.file }}"
        fi
      shell: bash
