name: Setup environment
description: Setup GO or NPM environment
inputs:
  enable_go:
    description: Whether to enable go specific features, such as caching.
    default: "false"
  go_version:
    description: The Go version to be used if Go is enable
    default: 1.24.x
  enable_go_cache:
    description: Whether you want to cache the go dependencies
    default: "true"
  enable_cue:
    description: Whether you want to install the cue binary
    default: "false"
  cue_version:
    description: The Cue version to be used if Cue is enable
    default: v0.8.0
  enable_npm:
    description: Whether to enable npm specific features, such as caching.
    default: "false"
  nvmrc_path:
    description: Path to the nvmrc file that contain the node version
    default: .nvmrc
runs:
  using: composite
  steps:
    - name: Install Go
      uses: actions/setup-go@v5
      if: inputs.enable_go == 'true'
      with:
        go-version: ${{ inputs.go_version }}
        cache: ${{ inputs.enable_go_cache }}
    - name: Install Cue
      if: ${{ inputs.enable_go == 'true' && inputs.enable_cue == 'true' }}
      run: go install cuelang.org/go/cmd/cue@${{  inputs.cue_version }}
      shell: bash
    - name: Install nodejs
      uses: actions/setup-node@v5
      if: inputs.enable_npm == 'true'
      with:
        node-version-file: ${{ inputs.nvmrc_path }}
        registry-url: "https://registry.npmjs.org"
    - name: Cache npm
      uses: actions/cache@v4.2.4
      if: inputs.enable_npm == 'true'
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
