name: Test Preview Dashboards
on:
  workflow_dispatch:  # Allow manual triggering
  push:
    branches:
      - main
      - release/*
      - snapshot/*
    tags:
      - v*
  pull_request:
  merge_group:
jobs:
  test-preview-dashboards:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install percli
        uses: ./actions/install_percli
        with:
          cli_version: "latest"

      - name: Test dashboard preview
        uses: ./actions/preview_dashboards
        with:
          url: https://demo.perses.dev
          file: ./testdata/resources_folder/dashboard.json
          username: test
          password: test

